import { hasEmail, hasPhone, hasWhatsapp, siteConfig, siteOrigin } from '../config/site.config'
import type { DigitalIconKey, ReasonIconKey } from '../components/iconRegistry'
import type { FaqItem } from './services'

/**
 * ---------------------------------------------------------------------------
 * SITE CONTENT — edit copy here.
 * ---------------------------------------------------------------------------
 * Everything a visitor reads that is not a short interface string comes from
 * this file and from `services.ts`, so wording can be changed without touching
 * a component.
 *
 * TRANSLATION MODEL
 *  The site is English only. `ui.ts` holds short chrome — button labels, nav,
 *  form labels, errors — and is read by key. This file holds long-form copy,
 *  stored as plain strings beside the components that render them, so a wording
 *  change is a one-line edit and there is no lookup layer to get wrong.
 *
 * WHAT IS DELIBERATELY NOT INVENTED ANYWHERE IN THIS FILE
 *  - Contact details and social profiles. They come from
 *    `src/config/site.config.ts` and are empty until real values are supplied,
 *    so the UI shows a labelled placeholder rather than a number that does not
 *    work.
 *  - Claims. No customer numbers, ratings, testimonials, awards, years of
 *    experience, government affiliation or success rates appear anywhere on
 *    this site, because none of them has been verified. Every point in `whyUs`
 *    and every line in `company` is a statement about how the work is
 *    organised, which is the only kind of claim that can be made honestly.
 *  - Published pricing. There is no price on this site, not even a "starting
 *    from". Work of this kind is quoted per engagement after the facts are
 *    known, and a figure on a web page is either a promise we cannot keep or a
 *    number the visitor then has to argue about.
 *  - Timelines and approvals. Both belong to the authority, not to us.
 *  - Testimonials. When real ones exist they go in `company.testimonials`. Until
 *    then the section says what we can actually stand behind, which is a far
 *    better answer than a paragraph of invented praise.
 */

// ============================================================================
// COMPANY
// ============================================================================

export const site = {
  name: siteConfig.COMPANY_NAME,
  /** The main promise, in the company's own words. */
  tagline: 'Registration, tax and compliance, handled properly.',
  /** Short supporting line for the footer and the meta description. */
  supportingLine:
    'Business registration, accounting, tax and compliance support for businesses across Kerala.',
  /**
   * The homepage `<title>`, the `og:title` and the `twitter:title`. They are one
   * string in one place because the crawler, the link unfurl and the browser tab
   * must never disagree, and the copy in `index.html` is the pre-JavaScript
   * version of the same value.
   */
  seoTitle: `Business Registration, Accounting & Compliance in Kerala | ${siteConfig.COMPANY_NAME}`,
  /**
   * The same for the meta description. No price and no promise of a timeline:
   * a search snippet that quotes either is a commitment the site cannot keep.
   */
  seoDescription:
    'LLP and company registration, GST, income tax, accounting, auditing, project reports and trademark support for businesses across Kerala. Talk to us on WhatsApp.',
  description:
    'Business registration, accounting, tax and compliance support for new and existing businesses across Kerala — LLP and company registration, GST, income tax, bookkeeping, auditing, project reports and trademark.',
  /**
   * The live origin, or an empty string until the domain is confirmed. While it
   * is empty the site withholds canonical and og:url tags and does not publish a
   * sitemap, rather than publishing a made-up address.
   */
  url: siteOrigin,
  /** The market the company actually serves. Deliberately not one city. */
  region: 'Kerala',
  market: 'All of Kerala',
  locale: 'en_IN',
} as const

export const brand = {
  logo: '/brand/logo.png',
  logoOnDark: '/brand/logo-white.png',
  mark: '/brand/mark.png',
  faviconPng: '/brand/favicon-32.png',
  faviconSvg: '/favicon.svg',
  appleTouchIcon: '/brand/apple-touch-icon.png',
  // Versioned filename. The card is regenerated by scripts/make-og-image.py and
  // published under a new name each time, because /brand/* is cached for a day
  // and every social platform caches the image URL for far longer than that.
  ogImage: '/brand/og-image-v2.png',
  ogImageAlt: `${siteConfig.COMPANY_NAME} logo in white on a deep navy ground, with shifranuhatech.com beneath it.`,
} as const

// ============================================================================
// CONTACT
// ============================================================================

/**
 * Sourced from `src/config/site.config.ts`. Every one is empty until the company
 * supplies it, and the UI degrades to a labelled placeholder instead of showing
 * a number that does not work.
 */
export const contact = {
  phone: siteConfig.PHONE_NUMBER,
  whatsapp: siteConfig.WHATSAPP_NUMBER,
  email: siteConfig.EMAIL,
  address: siteConfig.ADDRESS,
  /**
   * Deliberately not "24/7". The phone line and the WhatsApp number are open at
   * any hour, but the honest claim is when a reply comes, not when a message can
   * be sent — and "available 24/7" on a page whose primary button is WhatsApp
   * reads as "someone is on WhatsApp at 3am". Stating the honest version sets
   * that expectation before an enquiry is sent rather than after.
   *
   * The contact page omits the row entirely when this is empty, so it is only
   * ever shown if it says something true.
   */
  hours: 'Enquiries any time — we reply during working hours',
  serviceAreaTitle: 'Where we work',
  serviceAreaBody:
    'We work with businesses across Kerala, and remotely with businesses elsewhere in India. Registration work is filed with the appropriate central or state authority wherever you are based.',
  /**
   * The market as a whole. Listed once, rather than as a page per district:
   * thin location pages are worse than no location pages.
   */
  serviceAreas: ['All of Kerala'],
} as const

/**
 * The prefilled WhatsApp message used by every button that is *not* on a service
 * page — the navbar, the hero, the footer, the sticky bar and the contact page.
 *
 * It has to open a conversation rather than make a claim, and it names no
 * specific service, because at that point the visitor has not chosen one yet.
 * It does name what the business does, so the first thing read in the chat is
 * the reason they are there rather than a bare "hello".
 *
 * Every service page overrides it with a message about that service, as do the
 * two digital services, so a conversation always starts with the visitor's
 * actual interest already stated.
 */
export const enquiry = {
  whatsappMessage: 'Hi, I would like to know more about your business registration services.',
} as const

/** Lets the UI skip an entire contact block while a value is still blank. */
export const contactConfigured = {
  phone: hasPhone,
  email: hasEmail,
  whatsapp: hasWhatsapp,
  any: hasPhone || hasEmail || hasWhatsapp,
} as const

/** Social profiles — empty links are hidden rather than pointed anywhere fake. */
export const social = {
  linkedin: 'https://www.linkedin.com/company/shifra-nuha-technologies',
  facebook: 'https://www.facebook.com/people/Shifra-Nuha-Technologies/61595113285377/',
  instagram: 'https://www.instagram.com/shifranuhatechnologies/',
  x: '',
} as const

// ============================================================================
// NAVIGATION
// ============================================================================

export type NavItem = { to: string; label: string }

/**
 * Four items, and no more. Services, About Us, How We Work and Contact: two
 * destinations, one section of this page, and one page that holds the contact
 * details and the form.
 *
 * "How We Work" is an in-page anchor rather than its own route because three
 * steps do not need a page of their own — and because a nav item that scrolls
 * somewhere useful is better than a nav item that 404s.
 *
 * There is deliberately no services mega-menu. The nine service pages are all
 * listed on `/services`, in the footer, and on the homepage, so none of them is
 * more than one click away.
 */
export const nav: NavItem[] = [
  { to: '/services', label: 'Services' },
  { to: '/about', label: 'About Us' },
  { to: '/#how-it-works', label: 'How We Work' },
  { to: '/contact', label: 'Contact' },
]

// ============================================================================
// HOME — HERO
// ============================================================================

/**
 * The hero does one job: tell a first-time visitor within a few seconds what
 * this company does for a business, and make it trivial to start a
 * conversation.
 *
 * So it carries, in order: what this is, the headline, one paragraph that names
 * the actual service lines, the two buttons, and a short set of commitments.
 * Nothing else. The full service list moved to the Tier 1 grid and the footer,
 * where it cannot push the WhatsApp button below the fold on a phone.
 *
 * There is no price here, and no "starting from" line either. The work is
 * quoted per engagement once the facts are known; a number on the hero would be
 * a number we would have to defend in a message at eleven at night.
 */
export const hero = {
  eyebrow: 'Professional business services',
  heading: 'Business registration, accounting and legal compliance in Kerala',
  supporting:
    'We help new and existing businesses get registered, stay compliant and keep the paperwork in order. One point of contact from the first conversation to the finished documents.',
  /**
   * Statements about how we work rather than claims about our history, which is
   * why they are safe to make before anything has been measured.
   */
  points: [
    'One point of contact throughout',
    'Scope and cost agreed before we start',
    'Qualified professionals carry out regulated work',
  ],
} as const

// ============================================================================
// HOME — TIER 1: PROFESSIONAL SERVICES
// ============================================================================

/**
 * The professional services, front and centre. These are what the business
 * actually does, they are what an owner comes to us for, and every one of them
 * has its own page on the site.
 *
 * The order is roughly the order a business meets them in: get the entity
 * right, register for tax, keep the books, do the tax, prove it to an auditor
 * or a bank, then protect the name. That ordering is a small thing, but it is
 * the difference between a catalogue and a service map.
 */
export const coreSection = {
  eyebrow: 'Our services',
  title: 'Professional services for new and running businesses',
  intro:
    'Eight services, and between them most of what a small business needs done to its registrations, its books and its tax. Open any one to see what it covers, what it needs from you, and where the limits are.',
  /**
   * The single line under the grid. Partnership firm registration is a real
   * service with its own page, but it is a niche structure choice rather than
   * one of the eight things most businesses need, so it is linked rather than
   * given a card of its own.
   */
  footnoteLead: 'Also available:',
  footnote: 'Partnership firm registration',
  footnoteSlug: 'partnership-registration',
  footnoteBody:
    'for firms that are not incorporating — see the full service page for how a partnership compares to an LLP.',
} as const

// ============================================================================
// HOME — TIER 2: DIGITAL SERVICES
// ============================================================================

/**
 * Two things, and they are genuinely secondary. The professional work is what
 * the business is built on; this is the digital layer a business chooses once it
 * exists.
 *
 * It sits on the quiet surface, after the primary work has been established,
 * as two plain entries rather than a card grid — a grid of two would be a
 * mistake, and a grid of eight would be the generic startup landing page the
 * design is meant to avoid.
 */
export const digitalSection = {
  eyebrow: 'Secondary services',
  title: 'Digital services, when you are ready for them',
  intro:
    'Both of these are optional and neither is needed to get started. They are here because a business that is properly registered and still invisible online is leaving enquiries on the table.',
  items: [
    {
      icon: 'website',
      title: 'Business Websites',
      whatsappMessage: 'Hi, I am interested in a website for my business.',
      body: 'A straightforward, fast website for the business — the pages customers actually look for, structured so it can be found in search and maintained by your own staff.',
      points: [
        'Service pages written around what customers search for',
        'Mobile-first, with fast load on a phone connection',
        'A content structure your team can update without a developer',
      ],
    },
    {
      icon: 'automation',
      title: 'Business Automation & Digital Workflow',
      whatsappMessage: 'Hi, I am interested in business automation.',
      body: 'The repetitive part of running a business removed from a person’s day: enquiries captured, followed up on time, quotes and reminders issued, and the records written back where they belong.',
      points: [
        'Enquiry capture and follow-up, so nothing sits in a phone',
        'Quotes, invoices, reminders and routine reports on a schedule',
        'Hand-offs between WhatsApp, email and your accounting records',
      ],
    },
  ] as {
    icon: DigitalIconKey
    title: string
    whatsappMessage: string
    body: string
    points: string[]
  }[],
} as const

// ============================================================================
// HOME — HOW WE WORK
// ============================================================================

/**
 * Three steps, because three is what a person can hold in their head.
 *
 * There is no step four promising a delivery date: the timeline belongs to the
 * authority, and the note underneath says so. A registration business that
 * quotes a completion date it does not control loses the customer in the second
 * week.
 */
export const process = {
  eyebrow: 'How we work',
  title: 'Three steps, the same for almost everyone',
  intro:
    'What changes from one client to the next is the content of each step, because it depends on your business and on the authority involved. The shape of it does not.',
  steps: [
    {
      number: '01',
      title: 'Initial Consultation',
      body: 'We talk through what you are setting up or what has gone wrong, and what you actually need done. You get a straight answer on whether we are the right firm for it, and what it will involve, before anything is committed.',
    },
    {
      number: '02',
      title: 'Documentation & Filing',
      body: 'We tell you exactly what documents are needed and why, collect them digitally, prepare the forms and agreements, and file with the relevant authority. You can see what is going out before it goes out.',
    },
    {
      number: '03',
      title: 'Ongoing Compliance & Support',
      body: 'Returns, filings, renewals and deadlines are tracked on a calendar for you, with reminders before each one. The same person who did the registration stays on the work.',
    },
  ],
  /**
   * Stated plainly, because the most common thing a registration company
   * oversells is a date. Promising one we do not control is how a firm loses a
   * customer in week two.
   */
  note: 'We do not quote a guaranteed completion time. Processing time depends on the documentation, the authority involved and its workload — we will tell you what is realistic for your case instead.',
} as const

// ============================================================================
// HOME — WHY CHOOSE US
// ============================================================================

/**
 * Four points, all of them statements about how the work is organised. No
 * "Kerala's best", no client counts, no awards: none of them has been verified,
 * and a first-time business owner is exactly the person who checks.
 */
export const whyUs = {
  eyebrow: 'Why work with us',
  title: 'What you are actually getting',
  intro: 'Four things that decide whether a filing goes smoothly or turns into a runaround.',
  points: [
    {
      icon: 'chat',
      title: 'One point of contact',
      body: 'The person who takes your first message also sees the filing through. You are not explaining your business again to every new vendor.',
    },
    {
      icon: 'document',
      title: 'Scope agreed in writing',
      body: 'What we will do, what it costs and which parts involve an external professional are agreed before any work begins.',
    },
    {
      icon: 'shield',
      title: 'Qualified professionals on regulated work',
      body: 'Accounting, tax, audit, incorporation and IP work is carried out or supervised by the appropriate chartered accountant, company secretary or practitioner.',
    },
    {
      icon: 'steps',
      title: 'Deadlines tracked, not remembered',
      body: 'Returns, renewals and annual filings go on a calendar with a reminder ahead of each one, so compliance does not depend on someone remembering.',
    },
  ],
} as const

// ============================================================================
// HOME — COMPANY CONTEXT
// ============================================================================

/**
 * The "who we are" block. Deliberately free of statistics: the number of
 * businesses assisted, customer testimonials, review counts and professional
 * credentials all belong here when they are real, and none of them is real yet.
 * Rather than pad the section with placeholders a visitor would read as
 * failures, it makes the argument the business can actually make — that there
 * is a real person on the other end of the WhatsApp message.
 *
 * When a testimonial is collected, it belongs in `testimonials` below and in
 * the render inside `components/Company.tsx`. Inventing one instead is the
 * fastest way to lose a first-time business owner's trust.
 */
export const company = {
  eyebrow: 'About us',
  title: 'A small firm that tells you what it will and will not do',
  body: 'Shifra Nuha Technologies helps businesses across Kerala get properly registered, stay compliant, and keep the professional work in one place rather than split across a dozen vendors. Registration is where a relationship usually starts. It is not the whole of it.',
  points: [
    'You deal with the same person from the first message to the finished documents.',
    'We tell you what the documents are before you start gathering them, not after.',
    'If what you need is not something we handle, we will tell you that instead of selling it.',
    'We will tell you in advance which part of the work is being done by an external professional.',
  ],
  /**
   * Deliberately empty. Populate with real, attributable, verifiable quotes only
   * — name, business, and the words they actually said.
   */
  testimonials: [] as { quote: string; name: string; business: string }[],
  button: 'Talk to us on WhatsApp',
} as const

// ============================================================================
// HOME — FAQ
// ============================================================================

export const faqsSection = {
  eyebrow: 'FAQ',
  title: 'Questions we are asked most',
  intro: 'Answered honestly. Where the honest answer is "it depends", that is what it says.',
} as const

/**
 * The homepage FAQ. The first two are the questions a visitor always opens an
 * FAQ to check — what it costs, and how long it takes — and both get the answer
 * that is actually true rather than the one that closes a sale.
 */
export const faqs: FaqItem[] = [
  {
    question: 'How much do your services cost?',
    answer:
      'It depends on your situation, so we do not publish a figure that would only be right for one kind of case. The cost depends on the work involved, the number of people involved, the state, the transaction volume, and the government fees that apply at the time. Tell us what you need and we will prepare a written quotation for it, with government fees shown separately from our professional fee.',
  },
  {
    question: 'How long does registration take?',
    answer:
      'We do not quote a guaranteed timeline, because we do not control it. Processing time depends on how complete and correct the documentation is, on the authority handling the filing, and on its workload at the time. What we will do is tell you what is realistic for your specific case and keep you updated rather than going quiet.',
  },
  {
    question: 'What documents are required?',
    answer:
      'The exact list depends on the applicant and the business structure. For a company we normally need, for each director, PAN and Aadhaar (or passport), date of birth, a passport-size photograph, a signature, proof of current address, an email address and a mobile number — plus proof of the registered office address, a short description of the business activity, and two or three preferred names in order of preference. We send you the exact list for your registration before you start gathering anything.',
  },
  {
    question: 'Do I need to visit an office?',
    answer:
      'In most cases, no. We collect your documents digitally over WhatsApp or email, prepare the application and handle the filing, and you receive the registration documents the same way. If something in your case does need to be signed or verified in person, we will tell you exactly what and why before you pay anything.',
  },
  {
    question: 'Who actually does the work?',
    answer:
      'Some business services are regulated and must be performed or supervised by qualified professionals. Where that applies, the appropriate professional carries out the work — a chartered accountant for accounting, taxation, GST and audit-related work; a company secretary for incorporation and corporate compliance; a lawyer for agreements and contracts; and a trademark or IP professional for IP work. We coordinate the engagement and tell you in advance which part involves an external partner.',
  },
  {
    question: 'Can you help after registration?',
    answer:
      'Yes, and that is usually where the bulk of the work is. GST registration and return filing, accounting, bookkeeping, income tax support, auditing, project reports and trademark work are all services we handle, and the digital work — website and business automation — is available too. The same contact continues, so you are not explaining your business again to each new vendor.',
  },
]

// ============================================================================
// HOME — CLOSING CTA
// ============================================================================

export const cta = {
  title: 'Tell us what you need done',
  body: 'A short message is enough to start. We will tell you what applies, what it involves, and what it costs, before you commit to anything.',
  /**
   * The line under the buttons. It exists to remove the last objection to
   * sending a message: that this is the point at which we start selling.
   */
  note: 'There is no obligation to go ahead, and we will not put a figure on it until we have understood what the work actually involves.',
} as const

// ============================================================================
// /services
// ============================================================================

export const servicesPage = {
  eyebrow: 'Services',
  title: 'Business registration and professional services',
  intro:
    'Registration is where we start. The services below cover starting a business and keeping it properly run — open any one to see what it covers, what documents it needs, and what we will ask you for before we start.',
  /** Rendered above the grid, so the cost policy is visible up front. */
  pricingPolicy: {
    title: 'How we quote',
    body: 'There is no published price list, and we would rather explain why than look as though we have one. Professional fees depend on the scope of the work, the number of people involved, the state, the transaction volume and how much reconciliation is included. Government fees — filing fees, stamp duty and statutory charges — are always itemised separately from our own fee, never folded into a single figure. We prepare a written quotation once we understand the case, and that is the figure you are held to.',
  },
} as const

// ============================================================================
// /about
// ============================================================================

export const aboutPage = {
  eyebrow: 'About us',
  heading: 'A business partner, not just a service provider.',
  intro:
    'Shifra Nuha Technologies helps new and existing businesses across Kerala get properly registered, stay compliant, and keep the professional work in one place. Registration is where we start. It is not the whole relationship.',
  positioning: {
    title: 'How we describe ourselves',
    primary: 'We help businesses start properly, and stay that way.',
    secondary: 'Registration, tax, accounting and professional support — through one point of contact.',
    body: 'We are deliberately not positioned as only a web development agency, an accounting firm or a marketing agency. A business rarely needs one of those things. It usually needs the right combination, in the right order, coordinated properly — and that is a different job from selling any single one of them.',
  },
  boundaries: {
    title: 'How we work with professional partners',
    body: 'Some business services are regulated and must be performed or supervised by qualified professionals. Where that applies, we coordinate the work and the appropriate professional carries it out — a chartered accountant for accounting, taxation, GST and audit-related work; a company secretary for incorporation and corporate compliance; a lawyer for agreements and contracts; and a trademark or IP professional for IP work.',
    points: [
      'You deal with one point of contact for the whole project.',
      'Regulated work is performed or supervised by the appropriate qualified professional.',
      'We tell you in advance which part of the work involves an external partner.',
    ],
  },
  partners: {
    title: 'Who does what',
    intro: 'We work with a small network of trusted specialists rather than a large in-house team, so you get the right expertise without a large fixed cost. You will always be told which work is being handled by an external partner.',
    rows: [
      { role: 'Chartered Accountant', responsibility: 'Accounting, taxation, GST, audit-related work and financial statements' },
      { role: 'Company Secretary', responsibility: 'Incorporation and corporate compliance' },
      { role: 'Lawyer', responsibility: 'Agreements, contracts and other legal matters' },
      { role: 'Trademark / IP professional', responsibility: 'Trademark search, filing and representation' },
      { role: 'Design and creative', responsibility: 'Branding, logo and creative work' },
      { role: 'Marketing', responsibility: 'Advertising, lead generation and SEO' },
      { role: 'Technical team', responsibility: 'Websites, software, automation and integrations' },
    ],
  },
  journey: {
    title: 'How an engagement usually grows',
    intro: 'Most businesses do not need everything at once. The work usually moves in this order, and each stage feeds the next. We do not push the later stages onto anyone.',
    steps: [
      { title: 'Register', body: 'Company, LLP or partnership, plus GST' },
      { title: 'Comply', body: 'Accounting, bookkeeping, income tax, audit' },
      { title: 'Build', body: 'Branding, logo, website, email, WhatsApp Business' },
      { title: 'Grow', body: 'Facebook and Instagram ads, Google Ads, lead generation' },
      { title: 'Automate', body: 'CRM, WhatsApp automation, and workflow automation' },
    ],
  },
  closing: {
    title: 'Start with a conversation, not a commitment.',
    body: 'Tell us what you are dealing with. If it is not something we handle, we will say so rather than take the work and pass it on.',
  },
} as const

// ============================================================================
// /contact
// ============================================================================

/**
 * ---------------------------------------------------------------------------
 * /contact
 * ---------------------------------------------------------------------------
 * WHATSAPP-FIRST, NO FORM. The page answers one question — how do I get hold of
 * this business — and it answers it three times over: WhatsApp first, phone
 * second, email third for whoever prefers it. There is no form, so there is no
 * set of fields to read before the first message, and nothing for a visitor to
 * get wrong.
 *
 * The three route cards are descriptive rather than three more big buttons: the
 * call to action is the pair of buttons in the intro, and the cards explain what
 * each route is actually for so a visitor can pick the one that suits them.
 */
export const contactPage = {
  eyebrow: 'Contact',
  heading: 'Have questions about your business?',
  intro:
    'We are happy to help with business registration and our other services. WhatsApp is the fastest way to reach us — it is a short message rather than a form, and we read every one.',
  routes: [
    {
      icon: 'whatsapp',
      title: 'WhatsApp',
      lead: 'Fastest — usually the quickest reply',
      body: 'Opens a chat with a short message already written, so you can add a few lines about your business and send it. Best if you are on your phone and want an answer in the same conversation.',
      action: 'Message us on WhatsApp',
    },
    {
      icon: 'phone',
      title: 'Call',
      lead: 'Best if you want to talk it through',
      body: 'Reaches us directly and works well if you already know what you need and would rather settle it on a call than in writing.',
      action: 'Call us now',
    },
    {
      icon: 'email',
      title: 'Email',
      lead: 'For anything you want in writing',
      body: 'A business address you can use for documents, detailed questions, or anything that is easier to explain than to type into a chat. We read email too.',
      action: 'Write to us',
    },
  ],
  directTitle: 'Contact details',
  nextSteps: [
    {
      number: '01',
      title: 'You message us',
      body: 'Send a few lines on WhatsApp, call, or write by email. A short description of your business is enough to start.',
    },
    {
      number: '02',
      title: 'We review and respond',
      body: 'We understand the requirement, check what is actually needed, and reply with a suggested way forward.',
    },
    {
      number: '03',
      title: 'We agree the scope',
      body: 'Scope, cost and who will be involved are agreed before any work begins.',
    },
  ],
} as const

// ============================================================================
// FOOTER / UTILITY
// ============================================================================

export const footer = {
  blurb:
    'Business registration, accounting, tax and compliance support for new and existing businesses across Kerala.',
  servicesTitle: 'Services',
  contactTitle: 'Contact',
  legalTitle: 'Legal',
  legal: [
    { label: 'Privacy Policy', to: '/privacy' },
    { label: 'Terms & Conditions', to: '/terms' },
    { label: 'Disclaimer', to: '/disclaimer' },
  ],
} as const

export const notFound = {
  heading: 'Page not found',
  body: 'The page you are looking for does not exist or has moved. Try one of the services, or get in touch and we will point you to the right place.',
  button: 'Go to the homepage',
} as const

// Re-exported so the icon registries stay the single source of icon keys.
export type { DigitalIconKey, ReasonIconKey }